config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'shifts#index'
  
  get '/shifts/', to: 'shifts#index'
  get '/shifts/:first_name', to: 'shifts#show', as: 'employee_shifts'
  get '/shifts/pickup/:id', to: 'shifts#pickup', as: 'pickup_shift'
  
  get '/log_out', to: 'sessions#destroy', as: 'log_out'
  get '/log_in', to: 'sessions#new', as: 'log_in'
  
  get '/work_restriction/create/:employee_id/:date', to: 'work_restrictions#create', as: 'create_work_restriction'
  get '/work_restriction/destroy/:employee_id/:date', to: 'work_restrictions#destroy', as: 'destroy_work_restriction'
  
  get '/shift_swap/create/:original_shift_id/:new_shift_id', to: 'shift_swaps#create', as: 'create_shift_swap'
  get '/shift_swap/approve/:id', to: 'shift_swaps#approve', as: 'approve_shift_swap'
  get '/shift_swap/auto_swap/:id', to: 'shift_swaps#autoSwap', as: 'auto_shift_swap'
  
  get '/admin_actions/', to: 'admin_actions#index'
  get '/admin_actions/regenerate_schedules', to: 'admin_actions#regenerateSchedules', as: 'admin_actions_regenerate_path'
  get '/admin_actions/generate_schedules', to: 'admin_actions#generateSchedules', as: 'admin_actions_generate_path'
  
  resources :sessions
  resources :employees
end

app/models/shift.rb
class Shift < ActiveRecord::Base
  belongs_to :employee
  has_many :shift_swaps, -> { where "approved IS NULL" }, :foreign_key => "original_shift_id"
  
  validates_uniqueness_of :on_call_date, :on => :create
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  def index
    # including :employee to remove n+1 possibility...
    @shifts = Shift.includes(:employee, :shift_swaps, :employee => :work_restrictions).where("on_call_date > ? and on_call_date <= ?",Date.today,Date.today + 1.month).order(on_call_date: :asc)
    @current_shift = Shift.find_by on_call_date: Date.today
    
    if @shifts.last.on_call_date < Date.today.beginning_of_month.next_month
      # we're running out of shifts! generate more...
      ScheduleGenerator.instance.generateSchedule
    end
  end
  
  def show    
    # including :employee to remove n+1 possibility...
    @shifts = Shift.includes(:employee, :shift_swaps, :employee => :work_restrictions).where("on_call_date > ? and on_call_date <= ?", Date.today, Date.today + 1.month).where(:employees => {:first_name => params[:first_name]}).order(on_call_date: :asc)
    @hero = params[:first_name]
  end
  
  def pickup
    shift = Shift.find(params[:id])
    if shift
      shift.update({employee_id: current_user.id})
    end
    redirect_to shifts_path, :notice => "You have picked up a shift on #{shift.on_call_date}."
  end
  
  private
    def shift_params
      params.permit(:first_name,:id)
    end
end

app/views/shifts/index.erb
<div id="currentHeroJumbotron" class="jumbotron">
  <h2>Today's&nbsp;Support&nbsp;Hero</h2>
  <h1><%= @current_shift.employee.first_name %></h1>
</div>

<h3>All Heroes in <%= Date.today.strftime("%B") %></h3>

<script>
  $(document).ready(function(){    
    $('.shiftSwapRequestLink').click(function(e){
      e.preventDefault();
      var original_shift_id = $('.shiftSwapRequestLink').data('original_shift_id');
      
      $('.unavailableLink').hide() // this just cluttered the interface
      $('.shiftSwapRequestLink').hide();
      $('.shiftSwapCancelLink').each(function(){
        console.log($(this).data('shift_id'));
        if ($(this).data('shift_id') == original_shift_id) {
          $(this).show();
        }
      });           
      $('.shiftSwapConfirmLink').each(function(){                  
        $(this).attr("href","/shift_swap/create/"+original_shift_id+"/"+$(this).data('new_shift_id'));
      });
      $('.shiftSwapConfirmLink').show(); 
    });
    $('.shiftSwapCancelLink').click(function(e){
      e.preventDefault();
      
      $('.shiftSwapRequestLink').show();
      $('.unavailableLink').show()
      $('.shiftSwapCancelLink').hide();
      $('.shiftSwapConfirmLink').hide();
      
      $('.shiftSwapConfirmLink').each(function(){                  
        $(this).attr("href","");
      });
    });
    
  });  
</script>

<% # used to be in a partial, but became too different than it's other use-cases %>
<% @shifts.each do |shift| %>
  <% 
    if shift.on_call_date == Date.today
      class_assignment = "futureHero current"
    else
      class_assignment = "futureHero"
    end 
    
    unavailable = false
    if shift.employee.work_restrictions.find_by date: shift.on_call_date
      class_assignment = class_assignment + " unavailable"
      unavailable = true
    end
  %>
    <p class="<%= class_assignment %>">      
      <%= shift.on_call_date.strftime("%m/%d/%Y") %> | <%= shift.employee.first_name %>      
      <% if current_user and current_user.first_name == shift.employee.first_name and shift.on_call_date >= Date.today %> 
        <% # if logged in, and this shift belongs to the logged in user %>
        <span class="pull-right">                    
          <% if unavailable %>
            <%= link_to "I'm Available", destroy_work_restriction_path(current_user.id,shift.on_call_date), :class => "unavailableLink" %>            
          <% else %>
            <%= link_to "I'm Not Available", create_work_restriction_path(current_user.id,shift.on_call_date), :class => "unavailableLink" %>
          <% end %>
          <a class="shiftSwapRequestLink" data-original_shift_id="<%= shift.id %>" href="#">Request Shift Swap</a>
          <a class="shiftSwapCancelLink" data-shift_id="<%= shift.id %>" href="#">Cancel Shift Swap</a>
        </span>
      <% elsif current_user and current_user.first_name != shift.employee.first_name and shift.on_call_date > Date.today %>
        <% # if logged in, and if this shift doesn't belong to the logged in user %>
        <span class="pull-right">
          <a class="shiftSwapConfirmLink" data-new_shift_id="<%= shift.id %>" href="#">Select as New Shift</a>
          <% if unavailable %>
            <%= link_to "Pickup Shift", pickup_shift_path(shift.id) %>
          <% end %>
        </span>
      <% end %>
    </p>
<% end %>

app/views/shifts/index.html.erb
<% if @current_shift %>
  <div id="currentHeroJumbotron" class="jumbotron">
    <h2>Today's&nbsp;Support&nbsp;Hero</h2>
    <h1><%= @current_shift.employee.first_name %></h1>
  </div>
<% end %>

<h3>Upcoming Support Heroes</h3>

<script>
  $(document).ready(function(){    
    $('.shiftSwapRequestLink').click(function(e){
      e.preventDefault();
      var original_shift_id = $(this).data('original_shift_id');
      
      $('.unavailableLink').hide() // this just cluttered the interface
      $('.shiftSwapRequestLink').hide();
      $('.shiftSwapCancelLink').each(function(){
        if ($(this).data('shift_id') == original_shift_id) {
          $(this).show();
        }
      });           
      $('.shiftSwapConfirmLink').each(function(){                  
        $(this).attr("href","/shift_swap/create/"+original_shift_id+"/"+$(this).data('new_shift_id'));
      });
      $('.shiftSwapConfirmLink').show(); 
    });
    $('.shiftSwapCancelLink').click(function(e){
      e.preventDefault();
      
      $('.shiftSwapRequestLink').show();
      $('.unavailableLink').show()
      $('.shiftSwapCancelLink').hide();
      $('.shiftSwapConfirmLink').hide();
      
      $('.shiftSwapConfirmLink').each(function(){                  
        $(this).attr("href","");
      });
    });
    
  });  
</script>

<% # used to be in a partial, but became too different than it's other use-cases %>
<% @shifts.each do |shift| %>
  <% 
    if shift.on_call_date == Date.today
      class_assignment = "futureHero current"
    else
      class_assignment = "futureHero"
    end 
    
    unavailable = false
    if shift.employee.work_restrictions.select { |work_restriction| work_restriction.date == shift.on_call_date }.length > 0
      class_assignment = class_assignment + " unavailable"
      unavailable = true
    end
      
    pending_swap = false
    if shift.shift_swaps.length > 0
      pending_swap = true
      class_assignment = class_assignment + " pendingSwap"
    end
  %>
    <p class="<%= class_assignment %>">      
      <%= shift.on_call_date.strftime("%m/%d/%Y") %> | <%= shift.employee.first_name %>
      <% if pending_swap %>
        <span class="pendingSwapSpan">(pending swap)</span>
      <% end %>
      <% if current_user and current_user.first_name == shift.employee.first_name and shift.on_call_date >= Date.today %> 
        <% # if logged in, and this shift belongs to the logged in user %>
        <span class="pull-right">
          <% if !pending_swap %>
            <% if unavailable %>
              <%= link_to "I'm Available", destroy_work_restriction_path(current_user.id,shift.on_call_date), :class => "unavailableLink" %>            
            <% else %>
              <%= link_to "I'm Not Available", create_work_restriction_path(current_user.id,shift.on_call_date), :class => "unavailableLink" %>
            <% end %>
            <a class="shiftSwapRequestLink" data-original_shift_id="<%= shift.id %>" href="#">Request Shift Swap</a>
            <a class="shiftSwapCancelLink" data-shift_id="<%= shift.id %>" href="#">Cancel Shift Swap</a>
          <% end %>
        </span>
      <% elsif current_user and current_user.first_name != shift.employee.first_name and shift.on_call_date > Date.today %>
        <% # if logged in, and if this shift doesn't belong to the logged in user %>
        <span class="pull-right">
          <a class="shiftSwapConfirmLink" data-new_shift_id="<%= shift.id %>" href="#">Select as New Shift</a>
          <% if unavailable %>
            <%= link_to "Pickup Shift", pickup_shift_path(shift.id) %>
          <% end %>
        </span>
      <% end %>
    </p>
<% end %>

app/views/shifts/show.erb
<%= link_to "< Back to all shifts", shifts_path %>

<h2><%= @hero %>'s Support Hero Shifts</h2>

<% @shifts.each do |shift| %>
  <% 
    if shift.on_call_date == Date.today
      class_assignment = "futureHero current"
    else
      class_assignment = "futureHero"
    end 
    
    unavailable = false
    if shift.employee.work_restrictions.find_by date: shift.on_call_date
      class_assignment = class_assignment + " unavailable"
      unavailable = true
    end
  %>
    <p class="<%= class_assignment %>">      
      <%= shift.on_call_date.strftime("%m/%d/%Y") %> | <%= shift.employee.first_name %>      
      <% if current_user and current_user.first_name == shift.employee.first_name and shift.on_call_date >= Date.today %>        
        <span class="pull-right">                    
          <% if unavailable %>
            <%= link_to "I'm Available", destroy_work_restriction_path(current_user.id,shift.on_call_date), :class => "unavailableButton" %>            
          <% else %>
            <%= link_to "I'm Not Available", create_work_restriction_path(current_user.id,shift.on_call_date), :class => "unavailableButton" %>
          <% end %>
        </span>      
      <% end %>
    </p>
<% end %>

<%= link_to "< Back to all shifts", shifts_path %>

app/views/shifts/show.html.erb
<%= link_to "< Back to all shifts", shifts_path %>

<h2><%= @hero %>'s Support Hero Shifts</h2>

<% @shifts.each do |shift| %>
  <% 
    if shift.on_call_date == Date.today
      class_assignment = "futureHero current"
    else
      class_assignment = "futureHero"
    end 
    
    unavailable = false
    if shift.employee.work_restrictions.select { |work_restriction| work_restriction.date == shift.on_call_date }.length > 0
      class_assignment = class_assignment + " unavailable"
      unavailable = true
    end

    pending_swap = false
    if shift.shift_swaps.length > 0
      pending_swap = true
      class_assignment = class_assignment + " pendingSwap"
    end
  %>
    <p class="<%= class_assignment %>">      
      <%= shift.on_call_date.strftime("%m/%d/%Y") %> | <%= shift.employee.first_name %>    
      <% if pending_swap %>
        <span class="pendingSwapSpan">(pending swap)</span>
      <% end %>
      <% if current_user and current_user.first_name == shift.employee.first_name and shift.on_call_date >= Date.today %>        
        <span class="pull-right">                    
          <% if unavailable %>
            <%= link_to "I'm Available", destroy_work_restriction_path(current_user.id,shift.on_call_date), :class => "unavailableButton" %>            
          <% else %>
            <%= link_to "I'm Not Available", create_work_restriction_path(current_user.id,shift.on_call_date), :class => "unavailableButton" %>
          <% end %>
        </span>      
      <% end %>
    </p>
<% end %>

<%= link_to "< Back to all shifts", shifts_path %>