config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'shifts#index'
  
  get '/shifts/', to: 'shifts#index'
  get '/shifts/:first_name', to: 'shifts#show', as: 'employee_shifts'
  get '/shifts/pickup/:id', to: 'shifts#pickup', as: 'pickup_shift'
  
  get '/log_out', to: 'sessions#destroy', as: 'log_out'
  get '/log_in', to: 'sessions#new', as: 'log_in'
  
  get '/work_restriction/create/:employee_id/:date', to: 'work_restrictions#create', as: 'create_work_restriction'
  get '/work_restriction/destroy/:employee_id/:date', to: 'work_restrictions#destroy', as: 'destroy_work_restriction'
  
  get '/shift_swap/create/:original_shift_id/:new_shift_id', to: 'shift_swaps#create', as: 'create_shift_swap'
  get '/shift_swap/approve/:id', to: 'shift_swaps#approve', as: 'approve_shift_swap'
  get '/shift_swap/auto_swap/:id', to: 'shift_swaps#autoSwap', as: 'auto_shift_swap'
  
  get '/admin_actions/', to: 'admin_actions#index'
  get '/admin_actions/regenerate_schedules', to: 'admin_actions#regenerateSchedules', as: 'admin_actions_regenerate_path'
  get '/admin_actions/generate_schedules', to: 'admin_actions#generateSchedules', as: 'admin_actions_generate_path'
  
  resources :sessions
  resources :employees
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hero Duty</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="/">
          <span class="logo">HD</span>
        </a>
        <a class="navbar-brand" href="/">
          Hero Duty
        </a>      
      </div>
      <div class="navbar-text navbar-right">
        <% if current_user %>
          <span class="hidden-xs">Logged in as</span>
          <% if current_user.first_name == 'Admin' %>
            <%= link_to current_user.first_name + " (admin panel)", admin_actions_path, :class => "navbar-link" %>
          <% else %>
            <%= link_to current_user.first_name + " (view my shifts)", employee_shifts_path(current_user.first_name), :class => "navbar-link" %>
          <% end %>
          <div class="logLink">
            <%= link_to "Log out", log_out_path %>
          </div>          
        <% else %>        
          <div class="logLink">
            <%= link_to "Log in", log_in_path %>
          </div>
        <% end %>        
      </div>
    </div>
  </nav>
  <div class="container">
    <% if current_user and pending_shift_swaps and !Settings.autoswap_shift_when_unavailable  %>
      <% pending_shift_swaps.each do |swap| %>
        <div class="alert alert-notice  alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= swap.original_shift.employee.first_name %> wants to swap shifts with you! 
          Their <%= swap.original_shift.on_call_date %> shift for your <%= swap.new_shift.on_call_date %> shift.
          <%= link_to "Approve Swap", approve_shift_swap_path(swap.id) %>
        </div>
      <% end %>
    <% end %>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %> alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= value %>
      </div>    
    <% end %>
    <%= yield %>
  </div>
</body>
</html>